var emsgs = {

    "emsgs" : [
        {
            "eventtype" : "com.tradedesksoftware.ets.events.ETSRouteEvent",
            "timestamp" : 1509095814435,
            "userId" : 1,
            "groupId" : 1,
            "companyId" : 1,
            "strategy" : null,
            "ticket" : {
                "id" : 5,
                "ownerId" : 4,
                "companyId" : 1,
                "groupId" : 0,
                "accountid" : 1,
                "ticketTime" : 1509095814000,
                "instrument" : {
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 0,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : null,
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "status" : "NEW",
                "quantity" : 2,
                "price" : 5900.5,
                "side" : "SELL",
                "type" : "MARKET",
                "shcs" : null,
                "expirationDate" : 0,
                "displayedSize" : 0,
                "receivedMethod" : "ELECTRONIC",
                "stopPrice" : null,
                "timeInForceCode" : "DAY",
                "receivingTerminalID" : 0,
                "receivingDepartmentID" : 0,
                "doNotReduceCode" : "NONE",
                "ticketid" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "attributes" : {
                },
                "tmotriggerTime" : 0
            },
            "order" : {
                "id" : 5,
                "creationTime" : 1509095814520,
                "ticketId" : 5,
                "accountId" : 1,
                "companyId" : 1,
                "groupId" : 1,
                "orderId" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "custOrderId" : "c6d72f22-ab59-4566-8cc5-a6c93b2c22a8",
                "price" : 5900.5,
                "quantity" : 2,
                "side" : "SELL",
                "type" : "MARKET",
                "destinationId" : 1,
                "market" : 1,
                "instrument" : {
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 7,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : "BTCUSD",
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "tif" : "DAY",
                "expireTime" : 0,
                "ownerId" : 4,
                "stopPrice" : null,
                "dispQty" : 0,
                "state" : "SENDING",
                "lastState" : "NEW",
                "relatedOrderId" : 0,
                "capacity" : "AGENCY",
                "cpOrderId" : null,
                "notes" : null,
                "offset" : null,
                "execInst" : null,
                "quoteId" : null,
                "avgprice" : null,
                "cumqty" : 0,
                "leavesqty" : 0,
                "aon" : "false",
                "relatedClOrdId" : null,
                "active" : true
            },
            "relatedOrder" : null,
            "destination" : {
                "id" : 1,
                "name" : "Simulator",
                "state" : "ENABLED",
                "gateway" : "simulator",
                "canCreate" : false,
                "enabled" : true
            },
            "account" : {
                "id" : 1,
                "state" : "ENABLED",
                "number" : "1 - Simulator",
                "companyId" : 0,
                "name" : "Simulator",
                "margin" : 0,
                "currency" : "USD",
                "type" : "PROPRIETARY",
                "reuseFund" : null,
                "limit" : 0,
                "balance" : 0,
                "pandl" : null,
                "maxordersize" : 0,
                "maxposlimit" : 0,
                "lastUpdate" : 1501875643000
            },
            "type" : "NEWORDER"
        },
        {
            "eventtype" : "com.tradedesksoftware.ets.events.ETSExecutionEvent",
            "timestamp" : 1509095814567,
            "userId" : 1,
            "groupId" : 1,
            "companyId" : 1,
            "execution" : {
                "id" : 9,
                "companyId" : 1,
                "groupId" : 1,
                "ownerId" : 4,
                "orderid" : 5,
                "relatedOrderid" : 0,
                "time" : 1509095814582,
                "type" : "NEW",
                "initialState" : "SENDING",
                "finalState" : "OPEN",
                "execid" : "ABSYNP3000000001",
                "ourOrderid" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "cpOrderid" : 5,
                "origOrderid" : null,
                "message" : null,
                "lastPrice" : 0,
                "lastQuantity" : 0,
                "avgPrice" : 0,
                "cumQuantity" : 0,
                "leavesQuantity" : 2,
                "instrument" : {
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 0,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : null,
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "destinationid" : 1,
                "side" : "SELL",
                "relatedExecId" : null,
                "relatedid" : 0,
                "broken" : false,
                "possdup" : false,
                "accountNumber" : null,
                "historical" : false
            },
            "order" : {
                "id" : 5,
                "creationTime" : 1509095814520,
                "ticketId" : 5,
                "accountId" : 1,
                "companyId" : 1,
                "groupId" : 1,
                "orderId" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "custOrderId" : "c6d72f22-ab59-4566-8cc5-a6c93b2c22a8",
                "price" : 5900.5,
                "quantity" : 2,
                "side" : "SELL",
                "type" : "MARKET",
                "destinationId" : 1,
                "market" : 1,
                "instrument" : {
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 0,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : null,
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "tif" : "DAY",
                "expireTime" : 0,
                "ownerId" : 4,
                "stopPrice" : null,
                "dispQty" : 0,
                "state" : "OPEN",
                "lastState" : "SENDING",
                "relatedOrderId" : 0,
                "capacity" : "AGENCY",
                "cpOrderId" : 5,
                "notes" : null,
                "offset" : null,
                "execInst" : null,
                "quoteId" : null,
                "avgprice" : null,
                "cumqty" : 0,
                "leavesqty" : 2,
                "aon" : false,
                "relatedClOrdId" : null,
                "active" : true
            },
            "source" : null,
            "gateway" : null
        },
        {
            "eventtype" : "com.tradedesksoftware.ets.events.ETSExecutionEvent",
            "timestamp" : 1509095814600,
            "userId" : 1,
            "groupId" : 1,
            "companyId" : 1,
            "execution" : {
                "id" : 10,
                "companyId" : 1,
                "groupId" : 1,
                "ownerId" : 4,
                "orderid" : 5,
                "relatedOrderid" : 0,
                "time" : 1509095814600,
                "type" : "TRADE",
                "initialState" : "OPEN",
                "finalState" : "FILLED",
                "execid" : "ABSYNP3000000002",
                "ourOrderid" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "cpOrderid" : 5,
                "origOrderid" : null,
                "message" : null,
                "lastPrice" : 5900.5,
                "lastQuantity" : 2,
                "avgPrice" : 5900.5,
                "cumQuantity" : 2,
                "leavesQuantity" : 0,
                "instrument" : {
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 0,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : null,
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "destinationid" : 1,
                "side" : "SELL",
                "relatedExecId" : null,
                "relatedid" : 0,
                "broken" : false,
                "possdup" : false,
                "accountNumber" : null,
                "historical" : false
            },
            "order" : {
                "id" : 5,
                "creationTime" : 1509095814520,
                "ticketId" : 5,
                "accountId" : 1,
                "companyId" : 1,
                "groupId" : 1,
                "orderId" : {
                    "stringValue" : "AHBVJJ3000000001"
                },
                "custOrderId" : "c6d72f22-ab59-4566-8cc5-a6c93b2c22a8",
                "price" : 5900.5,
                "quantity" : 2,
                "side" : "SELL",
                "type" : "MARKET",
                "destinationId" : 1,
                "market" : 1,
                "instrument" : -{
                    "type" : "FOREIGNEXCHANGE",
                    "id" : 0,
                    "symbol" : "BTCUSD",
                    "baseSymbol" : null,
                    "exchangeid" : 1,
                    "underlyingid" : 0,
                    "attributes" : {
                    }
                },
                "tif" : "DAY",
                "expireTime" : 0,
                "ownerId" : 4,
                "stopPrice" : null,
                "dispQty" : 0,
                "state" : "FILLED",
                "lastState" : "OPEN",
                "relatedOrderId" : 0,
                "capacity" : "AGENCY",
                "cpOrderId" : 5,
                "notes" : null,
                "offset" : null,
                "execInst" : null,
                "quoteId" : null,
                "avgprice" : 5900.5,
                "cumqty" : 2,
                "leavesqty" : 0,
                "aon" : false,
                "relatedClOrdId" : null,
                "active" : false
            },
            "source" : null,
            "gateway" : null
        }
    ]

};